### ISSUE TITLE
Migration of jiva external provisioner fails due to old volume directory is not found in the node

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/upgrade#128]
Had Trying the non-csi jiva migration in a five node cluster followed by the document https://github.com/openebs/upgrade/blob/master/docs/migration.md#migrating-jiva-external-provisioned-volumes-to-jiva-csi-volumes-experimental 
-  Jiva volume policy mentioned in the migration document  is not working 
```
apiVersion: openebs.io/v1alpha1
kind: JivaVolumePolicy
metadata:
  name: example-jivavolumepolicy
  namespace: openebs
spec:
  replicaSC: openebs-hostpath
  target:
    # This should be same as the ReplicaCount
    # in the old StorageClass 
    replicationFactor: 1
```
Instead of that  used the below jiva csi volume policy. 
```
apiVersion: openebs.io/v1alpha1
kind: JivaVolumePolicy
metadata:
  name: migrate-jivavolumepolicy
  namespace: openebs
spec:
  replicaSC: openebs-hostpath
  enableBufio: false
  autoScaling: false
  target:
    # This should be same as the ReplicaCount
    # in the old StorageClass 
    replicationFactor: 3
```
Then followed the steps in the document mentioned that after scaled down the csi sts replica 
-  SSH into each node. Remove the files from the new localpv hostpath and copy the files from old hostpath to the new localpv hostpath While  trying not able to saw the non-csi volume path in the some nodes because of the following reason- Non csi replicas (old volume rep) presented in N1,N2,N3 and the new volume present in N2,N4,N5 so in N4 and N5 there is no old rep to move the files.
