### ISSUE TITLE
Error on upgrade from 2.12.2 to 3.0.0 - failed to get controller deployment for volume ***: no deployments found for label: *** in openebs namespace

### ISSUE THREAD

**Issue by juliohm1978** [openebs/upgrade#140]
**Describe the bug:**

I'm trying to upgrade volumes from a 2.12.2 installation, following instructions from here: https://github.com/openebs/upgrade/blob/develop/docs/upgrade.md#jiva-csi-volumes

Current 2.x installation was done using the official helm chart, without any modifications to the original values.yaml.

```
helm upgrade --install --create-namespace -n openebs  openebs openebs/openebs --version 2.12.2
```

OpenEBS was upgraded with a custom values.yaml to enable Jiva Operator and legacy controllers: [openebs-values.yaml.zip](https://github.com/openebs/upgrade/files/7559405/openebs-values.yaml.zip)

```
helm upgrade --install --create-namespace -n openebs  openebs openebs/openebs --version 3.0.3 -f openebs-values.yaml
```

At this point, legacy jiva PVs are still working and new PVs can be provisioned by the Jiva Operator.

The following error comes up while trying to upgrade legacy PVs, using the [upgrade tool](https://github.com/openebs/upgrade/blob/develop/examples/upgrade/jiva-volume.yaml),

```
E1118 02:25:42.970856       1 jiva_volume.go:71] failed to get controller deployment for volume pvc-6f494ad3-18e2-459a-b062-668c3f5fad57: no deployments found for label: openebs.io/component=jiva-controller,openebs.io/persistent-volume=pvc-6f494ad3-18e2-459a-b062-668c3f5fad57 in openebs namespace
```

Inspecting the pv controller, I can see the expected labels are not present in the controller pods.

```
kubectl get deploy -n openebs pvc-6f494ad3-18e2-459a-b062-668c3f5fad57-ctrl -oyaml

** snipped **

  labels:
    monitoring: volume_exporter_prometheus
    openebs.io/cas-template-name: jiva-volume-create-default-2.12.0
    openebs.io/cas-type: jiva
    openebs.io/controller: jiva-controller
    openebs.io/persistent-volume: pvc-6f494ad3-18e2-459a-b062-668c3f5fad57
    openebs.io/persistent-volume-claim: asdf
    openebs.io/storage-engine-type: jiva
    openebs.io/version: 2.12.0
```
I tried manually adding the missing `openebs.io/component=jiva-controller` label to the deployment, but that creates another error message.

```
E1118 02:49:49.631009       1 jiva_volume.go:71] failed to list replica statefulset for volumepvc-6f494ad3-18e2-459a-b062-668c3f5fad57: no statefulsets found for label: openebs.io/component=jiva-replica,openebs.io/persistent-volume=pvc-6f
494ad3-18e2-459a-b062-668c3f5fad57 in openebs namespace
```

**Expected behaviour:** I expected the upgrade tool to work without much modification from the default installation. Even the serviceaccount name in the example does not match what the helm chart created.

**Steps to reproduce the bug:**
Install OpenEBS using 2.12.2 chart.

```
helm upgrade --install --create-namespace -n openebs  openebs openebs/openebs --version 2.12.2
```

For simplicity, create a StorageClass with 1 replica.

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jiva1replica
  annotations:
    cas.openebs.io/config: |
      - name: FSType
        value: "xfs"
      - name: ReplicaCount
        value: "1"
      - name: StoragePool
        value: default
    openebs.io/cas-type: jiva
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
```

Create a PV using that storage class.

Upgrade to version 3.0.3 with Jiva enabled and legacy flag activated.

```yaml
# Legacy components will be installed if it is enabled.
# Legacy components are - admission-server, maya api-server, snapshot-operator
# and k8s-provisioner
legacy:
  enabled: true
```

```
helm upgrade --install --create-namespace -n openebs  openebs openebs/openebs --version 3.0.3 -f openebs-values.yaml
```

Attempt to migrate PV to the new Jiva operator.
